### ISSUE TITLE
[FR] Fallback to a CSS variable if no `level_color` is defined

### ISSUE THREAD

**Issue by ildar170975** [swingerman/lovelace-fluid-level-background-card#382] opened 2024-03-21 13:48 UTC
**Is your feature request related to a problem? Please describe.**

Currently a `level_color` option has a default value `rgb(0,128,0)`.
So, if the `level_color` is not defined explicitly - this default color is used.

Proposal:
Add a CSS variable like `--fluid-level-background-card-level-color` to a code:
- if no `level_color` option is defined: if this variable is defined -> then use this variable, otherwise - use a default color;
- if `level_color` option is defined -> then use this option (as it is implemented now).

Use-cases:
1. Similar to described in https://github.com/swingerman/lovelace-fluid-level-background-card/issues/381 (case 1) - but a user does not have to define a `level_color` for every card explicitly, everywhere a "standard water color" for a theme is used (assume this card is only used for a water).
2. Color of level may be changed dynamically by card-mod! Could be really cool - although a liquid color does not change dependently on a volume in a real life )))).
Consider the code:
```
  - type: custom:mod-card
    card_mod:
      style: |
        fluid-level-background-card {
          ... define --fluid-level-background-card-level-color dynamically dependently on a level's value ...
        }
    card:
      type: custom:fluid-level-background-card
      ... do not define level_color here
```

**Describe the solution you'd like**
Please see above.

**Describe alternatives you've considered**
-- none --

**Additional context**

**Comment by swingerman** [comment] 2024-03-21 14:38
I knew this was coming the moment I implemented the `background_color` fallback. 🤣

**Comment by swingerman** [comment] 2024-03-21 15:52
The severity based color is a duplicate of #134

**Comment by ildar170975** [comment] 2024-03-21 16:08
> The severity based color is a duplicate

Agree. But with card-mod we can define jinja-driven values, not hardcoded ones.
Just some more flexibility for this card.

**Comment by swingerman** [comment] 2024-03-21 17:21
Please check [v0.1.6-beta.2](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.2)

There is no fallback to a CSS variable currently, but maybe this satisfies your needs.

**Comment by ildar170975** [comment] 2024-03-21 18:27
The latest version does support CSS vars like:
```
level_color: var(--xxx-color)
```
So, we may define this `--xxx-color` variable in a theme & then use it in every card.

----------------

There is some limitation.
It is very specific & related to card-mod (i.e. - could be not crucial for 95% of users).
Consider this code:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sun.sun
        card_mod:
          style: |
            :host {color: var(--some-var);}
    card_mod:
      style: |
        ha-card {
          --some-var: red;
        }

  - type: custom:fluid-level-background-card
    card:
      type: glance
      entities:
        - entity: sun.sun
          name: Beer level
    entity: input_number.test_level_1
    fill_entity: input_boolean.test_boolean
    level_color: var(--some-var)

  - type: custom:mod-card
    card:
      type: custom:fluid-level-background-card
      card:
        type: glance
        entities:
          - entity: sun.sun
            name: Beer level
      entity: input_number.test_level_1
      fill_entity: input_boolean.test_boolean
      level_color: var(--some-var)
    card_mod:
      style: |
        ha-card {
          --some-var: magenta;
        }          
```
The `--some-var` is NOT defined in a theme.
In the 1st Entities card this variable is defined on a card's level as "red" -> then successfully used on a row's level.
In the 2nd `fluid-level` card the canvas is black - as expected since the variable is not defined.
But in the 3rd `fluid-level` card this variable is defined on a higher `mod-card` level - and this seems to be ignored.
My guess is that `level_color` is defined based on this variable on a card's construction stage - and any later changes are ignored. Means - we cannot play with this variable in card-mod as was [described here](https://github.com/swingerman/lovelace-fluid-level-background-card/issues/382#issue-2200252306).
Absolutely not crucial, just to clarify.

**Comment by swingerman** [comment] 2024-03-21 20:06
Have you tried to use the `:host` scope?:

```yaml
card_mod: 
  style: |
    :host {
       --some-var: magenta;
    }
```

**Comment by ildar170975** [comment] 2024-03-22 15:13
Tried these variants:
-- `:host` - then the variable is defined in a `mod-card` element (topmost level);
-- `ha-card` - in a `ha-card` of mod-card (2nd level);
-- `fluid-level-background-card` - topmost level of the "fluid" card.

In all cases the variable seems to be defined - example for `:host` is below:

![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/2af6e786-470f-4a2a-a10f-fafde83b414e)

But the variable is not used...
A white is used instead (even not a default `0,128,0`):

![изображение](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/8bd67fdc-9b9f-46e0-b4bf-bdee4c7703dc)

```
type: vertical-stack
cards:

  - type: custom:mod-card
    card:
      type: custom:fluid-level-background-card
      <<: &ref_settings
        card:
          type: glance
          entities:
            - entity: sun.sun
              name: Beer level
        entity: input_number.test_level_1
        fill_entity: input_boolean.test_boolean
        level_color: var(--my-color)
    card_mod:
      style: |
        :host {
          --my-color: magenta;
        }   

  - type: custom:mod-card
    card:
      type: custom:fluid-level-background-card
      <<: *ref_settings
    card_mod:
      style: |
        ha-card {
          --my-color: magenta;
        }          

  - type: custom:mod-card
    card:
      type: custom:fluid-level-background-card
      <<: *ref_settings
    card_mod:
      style: |
        fluid-level-background-card {
          --my-color: magenta;
        }          
```

**Closed** 2024-05-02 09:16 UTC
Labels: enhancement

**Comment by ildar170975** [comment] 2024-05-02 11:27
@swingerman 
Thanks for trying! Best wishes to Odessa.
