### ISSUE TITLE
Fill percentage shoud be independent of card size and aspect ratio.

### ISSUE THREAD

**Issue by kulmegil** [swingerman/lovelace-fluid-level-background-card#250] opened 2023-04-04 00:07 UTC
**Is your feature request related to a problem? Please describe.**
Fluid level fill % heavily depends on aspect ratio of containing card.
Aside from that actual width size seems to play a role to some extent.

* For a card of aspect ratio 16:9 the state value of 100 usually equals completely filled card.
 [screenshot - 100 percent](https://user-images.githubusercontent.com/570575/229651530-e92bdf52-6bd2-433c-9e58-a16dbd3a44e8.png)

* A card of 21:9 aspect ratio fills at around ≈ 85 percent
  [screenshot - 85 percent](https://user-images.githubusercontent.com/570575/229651875-d9eec06e-311d-4eed-9e93-64af70008512.png)

* a typical Tile card without AR on layout with extra space (~450px width) has filled as early as ≈ 65 percent
  [screenshot - 65 percent](https://user-images.githubusercontent.com/570575/229897830-282068ab-a7ae-4a74-9b24-24348aa0c3c8.png)
 
* A square card will never fill up. At the state value of 100 it's around 4/5 filled.

**Describe the solution you'd like**
A card should be filled based on enity state alone, independent of its size or aspect ratio.

**Describe alternatives you've considered**
Only way is to try create a card with "golden" aspect ratio, were the fluid level represents card filled %.

**Additional context**

**Comment by swingerman** [comment] 2023-04-04 14:52
Thanks for reporting this. I am aware of the issue and a work is in progress to fix it.

**Comment by swingerman** [comment] 2023-04-04 14:55
Duplicate of #205

**Comment by KiimaRo** [comment] 2023-11-07 10:47
Any news on when the heck this will be fixed?

**Comment by swingerman** [comment] 2023-11-24 21:59
resolved in #328

**Closed by swingerman** 2023-11-24 21:59 UTC
